using Galactica;

Star sun = new();
sun.Temperature = 100000;
sun.Name = "Sun";
sun.Type = Startype.YellowDwarf;
sun.Id = 0;
Console.WriteLine($"Star name: {sun.Name}\n- temperature: {sun.Temperature}\n- type: {sun.Type}");

Planet mercury = new();
mercury.Name = "Mercury";
mercury.Type = Planet.PlanetType.Terrestial;
mercury.Id = 1;
mercury.PlanetPosition = new();
mercury.PlanetPosition.X = 30;
mercury.PlanetPosition.Y = 100;
mercury.Diameter = 50;
mercury.RotationPeriod = 17;
mercury.RevolutionPeriod = 316;
sun.Planets.Add(mercury);
Console.WriteLine("\n" + mercury.Name);
Console.WriteLine($"- Type: {mercury.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + mercury.Distance(mercury.PlanetPosition.X, mercury.PlanetPosition.Y));
Console.WriteLine("- Position: " + mercury.PlanetPosition);

Planet venus = new();
venus.Name = "Venus";
venus.Type = Planet.PlanetType.Terrestial;
venus.Id = 2;
venus.PlanetPosition = new();
venus.PlanetPosition.X = 20;
venus.PlanetPosition.Y = 90;
venus.Diameter = 60;
venus.RotationPeriod = 19;
venus.RevolutionPeriod = 322;
sun.Planets.Add(venus);
Console.WriteLine("\n" + venus.Name);
Console.WriteLine($"- Type: {venus.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + venus.Distance(venus.PlanetPosition.X, venus.PlanetPosition.Y));
Console.WriteLine("- Position: " + venus.PlanetPosition);

Planet earth = new();
earth.Name = "Earth";
earth.Type = Planet.PlanetType.Terrestial;
earth.Id = 3;
earth.PlanetPosition = new();
earth.PlanetPosition.X = 10;
venus.PlanetPosition.Y = 900;
earth.Diameter = 23;
earth.RotationPeriod = 24;
earth.RevolutionPeriod = 365;
sun.Planets.Add(earth);
Console.WriteLine("\n" + earth.Name);
Console.WriteLine($"- Type {earth.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + earth.Distance(venus.PlanetPosition.X, earth.PlanetPosition.Y));
Console.WriteLine("- Position: " + earth.PlanetPosition);

Planet mars = new();
mars.Name = "Mars";
mars.Type = Planet.PlanetType.Terrestial;
mars.Id = 4;
mars.PlanetPosition = new();
mars.PlanetPosition.X = 200;
mars.PlanetPosition.Y = 93;
mars.Diameter = 20;
mars.RotationPeriod = 120;
mars.RevolutionPeriod = 321;
sun.Planets.Add(mars);
Console.WriteLine("\n" + mars.Name);
Console.WriteLine($"- Type: {mars.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + mars.Distance(mars.PlanetPosition.X, mars.PlanetPosition.Y));
Console.WriteLine("- Position: " + mars.PlanetPosition);

Planet jupiter = new();
jupiter.Name = "Jupiter";
jupiter.Type = Planet.PlanetType.Gas_Giant;
jupiter.Id = 5;
jupiter.PlanetPosition = new();
jupiter.PlanetPosition.X = 372;
jupiter.PlanetPosition.Y = 343;
jupiter.Diameter = 6000;
jupiter.RotationPeriod = 1;
jupiter.RevolutionPeriod = 322;
sun.Planets.Add(jupiter);
Console.WriteLine("\n" + jupiter.Name);
Console.WriteLine($"- Type: {jupiter.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + jupiter.Distance(jupiter.PlanetPosition.X, jupiter.PlanetPosition.Y));
Console.WriteLine("- Position: " + jupiter.PlanetPosition);

Planet saturn = new();
saturn.Name = "Saturn";
saturn.Type = Planet.PlanetType.Giant;
saturn.Id = 6;
saturn.PlanetPosition = new();
saturn.PlanetPosition.X = 54;
saturn.PlanetPosition.Y = 574;
saturn.Diameter = 867;
saturn.RotationPeriod = 75;
saturn.RevolutionPeriod = 392;
sun.Planets.Add(saturn);
Console.WriteLine("\n" + saturn.Name);
Console.WriteLine($"- Type: {saturn.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + saturn.Distance(saturn.PlanetPosition.X, saturn.PlanetPosition.Y));
Console.WriteLine("- Position: " + saturn.PlanetPosition);

Planet uranus = new();
uranus.Name = "Uranus";
uranus.Type = Planet.PlanetType.Giant;
uranus.Id = 7;
uranus.PlanetPosition = new();
uranus.PlanetPosition.X = 57;
uranus.PlanetPosition.Y = 370;
uranus.Diameter = 610;
uranus.RotationPeriod = 191;
uranus.RevolutionPeriod = 32;
sun.Planets.Add(uranus);
Console.WriteLine("\n" + uranus.Name);
Console.WriteLine($"- Type: {uranus.Type}");
Console.WriteLine($"- Distance to {uranus.Name}: " + uranus.Distance(uranus.PlanetPosition.X, uranus.PlanetPosition.Y));
Console.WriteLine("- Position: " + uranus.PlanetPosition);

Planet neptune = new();
neptune.Name = "Neptune";
neptune.Type = Planet.PlanetType.Dwarf;
neptune.Id = 8;
neptune.PlanetPosition = new();
neptune.PlanetPosition.X = 900;
neptune.PlanetPosition.Y = 92;
neptune.Diameter = 620;
neptune.RotationPeriod = 62;
neptune.RevolutionPeriod = 7822;
sun.Planets.Add(neptune);
Console.WriteLine("\n" + neptune.Name);
Console.WriteLine($"- Type: {neptune.Type}");
Console.WriteLine($"- Distance to {sun.Name}: " + neptune.Distance(neptune.PlanetPosition.X, neptune.PlanetPosition.Y));
Console.WriteLine("- Position: " + neptune.PlanetPosition);

Moon luna = new();
luna.Name = "Luna";
luna.Orbiting = mercury;
luna.PlanetPosition = new();
luna.PlanetPosition.X = 50;
luna.PlanetPosition.Y = 120;
mercury.Moons.Add(luna);
Console.WriteLine("\n" + luna.Name + ", orbiting the planet " + luna.Orbiting.Name);
Console.WriteLine($"- Distance to {luna.Orbiting.Name}: " + luna.Distance(luna.PlanetPosition.X, mercury.PlanetPosition.X, luna.PlanetPosition.Y, mercury.PlanetPosition.Y));
Console.WriteLine("- Position: " + luna.PlanetPosition);

Moon titan = new();
titan.Name = "Titan";
titan.Orbiting = earth;
titan.PlanetPosition = new();
titan.PlanetPosition.X = 10;
titan.PlanetPosition.Y = 120;
earth.Moons.Add(titan);
Console.WriteLine("\n" + titan.Name + ", orbiting the planet " + titan.Orbiting.Name);
Console.WriteLine($"- Distance to {titan.Orbiting.Name}: " + titan.Distance(titan.PlanetPosition.X, earth.PlanetPosition.X, titan.PlanetPosition.Y, earth.PlanetPosition.Y));
Console.WriteLine("- Position: " + titan.PlanetPosition);

Moon phobos = new();
phobos.Name = "Phobos";
phobos.Orbiting = jupiter;
phobos.PlanetPosition = new();
phobos.PlanetPosition.X = 510;
phobos.PlanetPosition.Y = 320;
jupiter.Moons.Add(phobos);
Console.WriteLine("\n" + phobos.Name + ", orbiting the planet " + phobos.Orbiting.Name);
Console.WriteLine($"- Distance to {phobos.Orbiting.Name}: " + phobos.Distance(phobos.PlanetPosition.X, jupiter.PlanetPosition.X, phobos.PlanetPosition.Y, jupiter.PlanetPosition.Y));
Console.WriteLine("- Position: " + phobos.PlanetPosition);

Moon europe = new();
europe.Name = "Ëurope";
europe.Orbiting = saturn;
europe.PlanetPosition = new();
europe.PlanetPosition.X = 150;
europe.PlanetPosition.Y = 1230;
mercury.Moons.Add(europe);
Console.WriteLine("\n" + europe.Name + ", orbiting the planet " + europe.Orbiting.Name);
Console.WriteLine($"- Distance to {europe.Orbiting.Name}: " + europe.Distance(europe.PlanetPosition.X, mercury.PlanetPosition.X, europe.PlanetPosition.Y, mercury.PlanetPosition.Y));
Console.WriteLine("- Position: " + europe.PlanetPosition);

Moon deimos = new();
deimos.Name = "Deimos";
deimos.Orbiting = earth;
deimos.PlanetPosition = new();
deimos.PlanetPosition.X = 50;
deimos.PlanetPosition.Y = 120;
earth.Moons.Add(deimos);
Console.WriteLine("\n" + deimos.Name + ", orbiting the planet " + deimos.Orbiting.Name);
Console.WriteLine($"- Distance to {deimos.Orbiting.Name}: " + deimos.Distance(deimos.PlanetPosition.X, earth.PlanetPosition.X, deimos.PlanetPosition.Y, earth.PlanetPosition.Y));
Console.WriteLine("- Position: " + deimos.PlanetPosition);

Moon ganymedes = new();
ganymedes.Name = "Ganymedes";
ganymedes.Orbiting = jupiter;
ganymedes.PlanetPosition = new();
ganymedes.PlanetPosition.X = 5290;
ganymedes.PlanetPosition.Y = 1230;
jupiter.Moons.Add(ganymedes);
Console.WriteLine("\n" + ganymedes.Name + ", orbiting the planet " + ganymedes.Orbiting.Name);
Console.WriteLine($"- Distance to {ganymedes.Orbiting.Name}: " + ganymedes.Distance(ganymedes.PlanetPosition.X, jupiter.PlanetPosition.X, ganymedes.PlanetPosition.Y, jupiter.PlanetPosition.Y));
Console.WriteLine("- Position: " + ganymedes.PlanetPosition);

Moon io = new();
io.Name = "Io";
io.Orbiting = mercury;
io.PlanetPosition = new();
io.PlanetPosition.X = 29;
io.PlanetPosition.Y = 20;
mercury.Moons.Add(io);
Console.WriteLine("\n" + io.Name + ", orbiting the planet " + io.Orbiting.Name);
Console.WriteLine($"- Distance to {io.Orbiting.Name}: " + io.Distance(io.PlanetPosition.X, mercury.PlanetPosition.X, io.PlanetPosition.Y, mercury.PlanetPosition.Y));
Console.WriteLine("- Position: " + io.PlanetPosition);

Moon mimas = new();
mimas.Name = "Mimas";
mimas.Orbiting = uranus;
mimas.PlanetPosition = new();
mimas.PlanetPosition.X = 42;
mimas.PlanetPosition.Y = 786;
uranus.Moons.Add(mimas);
Console.WriteLine("\n" + mimas.Name + ", orbiting the planet " + mimas.Orbiting.Name);
Console.WriteLine($"- Distance to {mimas.Orbiting.Name}: " + mimas.Distance(mimas.PlanetPosition.X, uranus.PlanetPosition.X, mimas.PlanetPosition.Y, uranus.PlanetPosition.Y));
Console.WriteLine("- Position: " + mimas.PlanetPosition);
